name: Test BTC Price Fetch

on:
  workflow_dispatch:

jobs:
  fetch-price:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch BTC price
        run: |
          PRICE=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd" | jq '.bitcoin.usd')
          echo "BTC price is: $PRICE"
