- name: Update data.csv with today's BTC price
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          PRICE=${{ env.price }}
          python3 - << EOF
import csv

with open('data.csv', newline='') as f:
    reader = list(csv.reader(f))
headers = reader[0]
rows = reader[1:]

date_idx = headers.index('date')
actual_idx = headers.index('btc_actual')

today = "$DATE"
price = float("$PRICE")
found = False

for r in rows:
    if r[date_idx] == today:
        found = True
        if not r[actual_idx]:
            r[actual_idx] = str(price)

if not found:
    rows.append([today] + ['']*(len(headers)-2) + [str(price), ''])

with open('data.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(headers)
    writer.writerows(rows)
EOF
