name: BTC Data Update Test

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch BTC price
        id: price
        run: |
          PRICE=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd" | jq '.bitcoin.usd')
          echo "price=$PRICE" >> $GITHUB_ENV

      - name: Append to data.csv
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          PRICE=$price
          echo "$DATE,,,,,$PRICE," >> data.csv

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "actions@github.com"
          git add data.csv
          git diff --quiet || git commit -m "chore: append BTC price for $DATE"
          git push
