name: Hello World Test

on:
  workflow_dispatch:
  schedule:
    - cron: 4 14 * * *'  # каждый день в 12:00 UTC

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions!"
