name: BTC Data Patch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch BTC price
        id: fetch
        run: |
          PRICE=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd" | jq '.bitcoin.usd')
          echo "price=$PRICE" >> $GITHUB_ENV

      - name: Patch data.csv with BTC actual
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          PRICE=$price
          python3 - <<EOF
import csv

date = "$DATE"
price = "$PRICE"

with open('data.csv', newline='') as f:
    rows = list(csv.reader(f))

headers = rows[0]
date_idx = headers.index("date")
actual_idx = headers.index("btc_actual")

found = False
for r in rows[1:]:
    if r[date_idx] == date:
        if not r[actual_idx]:
            r[actual_idx] = price
        found = True
        break

if not found:
    rows.append([date, '', '', '', '', price, ''])

with open('data.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(rows)
EOF

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "actions@github.com"
          git add data.csv
          git diff --quiet || git commit -m "chore: update BTC actual for $DATE"
          git push
