name: Daily BTC Update

on:
  schedule:
    - cron: '0 23 * * *'  # каждый день в 23:00 UTC
  workflow_dispatch:

jobs:
  update-btc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch BTC closing price
        id: fetch_price
        run: |
          PRICE=$(curl -s 'https://api.coingecko.com/api/v3/coins/bitcoin/history?date='$(date -d "yesterday" +'%d-%m-%Y') | jq '.market_data.current_price.usd')
          echo "::set-output name=price::$PRICE"
      - name: Update data.csv
        run: |
          PRICE=${{ steps.fetch_price.outputs.price }}
          DATE=$(date -d "yesterday" +'%Y-%m-%d')
          echo "Appending actual price for $DATE: $PRICE"
          MA=$(awk -F',' -v d="$DATE" -v p="$PRICE" '
            BEGIN{sum=0;count=0}
            {rows[NR]=$0}
            END{
              for(i=NR-29;i<=NR;i++){
                split(rows[i], a,",")
                if(a[6] != "" && a[6] !="---"){
                  sum+=a[6]; count++
                }
              }
              if(count<30){ma="---"} else ma=sprintf("%.2f", sum/count)
              print ma
            }
          ' data.csv)
          awk -F',' -v d="$DATE" -v p="$PRICE" -v ma="$MA" '
            BEGIN{OFS=","}
            { if($1==d){
                $6=p; $7=ma
              }
              print
            }' data.csv > tmp.csv && mv tmp.csv data.csv
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add data.csv
          git commit -m "Daily update BTC actual & MA for $(date -d "yesterday" +'%Y-%m-%d')" || echo "No changes"
          git push
