name: Daily BTC Update

on:
  schedule:
    - cron: '4 13 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch BTC price
        id: price
        run: |
          echo "Fetching BTC price..."
          PRICE=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd" | jq '.bitcoin.usd')
          echo "price=$PRICE" >> $GITHUB_OUTPUT

      - name: Update data.csv
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          PRICE="${{ steps.price.outputs.price }}"
          python3 - << 'EOF'
import csv
from statistics import mean

filename = "data.csv"

with open(filename, newline="") as f:
    rows = list(csv.reader(f))

headers = rows[0]
rows = rows[1:]

today = "$DATE"
price = "$PRICE"

if today not in [r[0] for r in rows]:
    rows.append([today] + [''] * (len(headers) - 2) + [price, ''])

actual_idx = headers.index("btc_actual")
ma_idx = headers.index("moving_average")

for i, r in enumerate(rows):
    if i + 1 >= 30:
        window = [float(x[actual_idx]) for x in rows[i - 29:i + 1] if x[actual_idx]]
        if len(window) == 30:
            r[ma_idx] = f"{mean(window):.2f}"

with open(filename, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(headers)
    writer.writerows(rows)
EOF

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "actions@github.com"
          git add data.csv
          git diff --quiet || git commit -m "chore: daily update BTC"
          git push
