name: Daily BTC Update

on:
  schedule:
    - cron: '8 13 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch BTC price
        id: fetch_price
        run: |
          echo "Getting BTC price..."
          price=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd" | jq '.bitcoin.usd')
          echo "price=$price" >> $GITHUB_ENV

      - name: Update data.csv
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          PRICE=$price

          python3 <<EOF
import csv
from statistics import mean

date = "$DATE"
price = "$PRICE"

with open("data.csv", newline="") as f:
    rows = list(csv.reader(f))

headers = rows[0]
data = rows[1:]

dates = [row[0] for row in data]
if date not in dates:
    data.append([date] + [''] * (len(headers) - 2) + [price, ''])

actual_index = headers.index("btc_actual")
ma_index = headers.index("moving_average")

for i in range(len(data)):
    if i >= 29 and not data[i][ma_index]:
        try:
            window = [float(data[j][actual_index]) for j in range(i - 29, i + 1) if data[j][actual_index]]
            if len(window) == 30:
                data[i][ma_index] = f"{mean(window):.2f}"
        except:
            pass

with open("data.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(headers)
    writer.writerows(data)
EOF

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data.csv
          git diff --cached --quiet || git commit -m "chore: update BTC price for $DATE"
          git push
